---
title: "EDS 221: Day 8 Interactive"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# install new plotting packages
# install.packages("patchwork")
# install.packages("ggrepel")
# install.packages("gghighlight")
# install.packages("paletteer")
# install.packages("ggExtra")
# install.packages("ggbeeswarm")
```

```{r}
# attach packages
library(tidyverse)
library(here)
library(janitor)
library("patchwork")
library("ggrepel")
library("gghighlight")
library("paletteer")
library("ggExtra")
library("ggbeeswarm")
```


```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

```{r}
ggplot(lizards, aes(total_length, weight)) + 
  geom_point() +
  geom_line()

ggplot(lizards) + 
  geom_point(aes(total_length, weight)) 

ggplot() + 
  geom_point(lizards, aes(total_length, weight))
```

```{r}
ggplot(data=lizards, aes(total_length)) +
  geom_histogram()
```


Jitter plots are best with on continuous and one categorical 

```{r}
# good
ggplot(lizards, aes(weight, common_name))+
  geom_jitter(aes(color=common_name))
# bad 
ggplot(lizards, aes(weight, common_name))+
  geom_point()
```


```{r}
ggplot(lizards, aes(weight))+
  geom_histogram(color="orange", 
                 fill="purple",
                 linewidth=2,
                 linetype="dotted")
```

```{r}
ggplot(lizards, aes(total_length, weight)) +
  geom_point(color="#DDC3D0",
             fill="#3E92CC",
             shape=22,
             size=5,
             alpha=0.2)
```

```{r}
ggplot(lizards, aes(total_length, weight)) +
  geom_point(aes(color = common_name, 
                 size = total_length),
             alpha = 0.5)+
  scale_color_discrete(type = c("#AA4465","#EDF0DA","#EDF0DA",
                                  "#EDF0DA","#EDF0DA","#EDF0DA","#EDF0DA"))
  # scale_color_brewer(palette = "Set3")
```

```{r}
ggplot(lizards, aes(site,weight)) +
  geom_jitter(aes(color=common_name)) +
  theme_light()
```

```{r}
ggplot(lizards, aes(total_length,weight)) +
  geom_point() +
  labs(x="Total Length (mm)",
       y="Weight (grams)",
       title="Lizard Size")

```



```{r}
# ~ acts as group by, filters by matrix
ggplot(lizards, aes(total_length, weight)) +
  geom_point() +
  facet_wrap(~common_name, ncol=3, scales = "free") +
  labs(x="Total length (mm)",
       y="Weight (grams")
```

```{r}
ggplot(lizards, aes(total_length, weight)) +
  geom_point()+
  facet_grid(sex ~ tail)
```

```{r}
# make a geo bar graph with viz in order of count instead of alphabetical order
lizards_counts <- lizards |> 
  count(common_name) |> 
  rename(n_lizards = n)

ggplot(lizards_counts, aes(n_lizards, fct_reorder(common_name, n_lizards))) +
  geom_col()
```

```{r}
ggplot(lizards, aes(total_length, weight)) +
  geom_point(aes(color = common_name),
             size=2) +
  theme_minimal() +
  labs(x="Total length (mm",
       y= "Weight (g)",
       color = "Lizard species") +
  facet_wrap(~common_name, scales="free")
```

```{r}
# ~ acts as group by, filters by matrix
# b w 
#    f
#    j
#    m
ggplot(lizards, aes(y=fct_infreq(common_name))) +
  geom_bar(aes(fill=site)) +
  theme_minimal() +
  labs(x= "Lizard counts",
       y= "Species (common name)") +
  facet_grid(sex~tail)
```

```{r}
ggplot(lizards, aes(total_length, weight))+
  geom_point()+
  scale_x_continuous(breaks = seq(0,500,250),
                     limit = c(0,500)) +
  scale_y_continuous(breaks = seq(0,70,10),
                     limits = c(0,70)) +
  theme_light()
```

```{r}
lizards_counts <- lizards |> 
  mutate(date=lubridate::mdy(date)) |> 
  count(date)

ggplot(lizards_counts, aes(date, n)) +
  geom_line() +
  scale_x_date(breaks= scales::breaks_pretty()) + 
  #scale_x_date(breaks= scales::breaks_width("3 years"),
               #labels= scales::label_date("'%y")) +
  labs(x = "Date",
       y = "Number of lizards (n)")
```

```{r}
ggplot(lizards, aes(total_length, weight)) +
  geom_point(aes(color=weight)) +
  scale_color_steps(low = "red", high = "black")
  #scale_color_gradientn(colors = c("orange", "red", "purple", "navy", "black"))
  #scale_color_gradient(low = "red", high = "navy")
```


```{r}
p <- ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point()

p + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "red"),
        plot.background = element_rect(fill="pink"),
        text= element_text(size= 12, family = 'serif'),
        axis.text.x= element_text(color = "blue"),
        axis.text.y = element_text(color= "green"),
        panel.background = element_rect(color="purple", fill = "yellow"))
```

```{r}
p +
  geom_hline(yintercept = mean(lizards$weight), color = "blue", linetype = "dashed") +
  #geom_vline(xintercept = 100, color = 'red') +
  #annotate("text", x=100, y=50, label = "COOL!", color = "purple") +
  annotate("text", x=350, y= mean(lizards$weight)+2, label = "Mean weight")
```

```{r}
mono <- read_csv(here("data_tidy", "mono.csv"))

ggplot(mono, aes(year, lake_level)) +
  geom_rect(aes(xmin = 1941, xmax = 1983,
                ymin = 6350, ymax = 6440),
                fill = "gray90", alpha= .5) +
  geom_line() +
  labs(x="Year",
       y="Lake suface level\n(feet above sea level)",
       title="Mono Lake (1850-2017)",
       caption="Data: Mono Basin Clearinghouse") +
  scale_y_continuous(limits = c(6350, 6440),
                     breaks = c(6370, 6400,  6430),
                     labels = scales::label_comma()) +
  scale_x_continuous(limits = c(1850, 2020),
                     breaks = seq(1850, 2010, 20),
                     expand = c(0,0)) +
  geom_hline(yintercept = 6360, linetype= "dashed") +
  annotate("text", x=1910, y=6370,
           label = "Decreased Shrimp abundance expected\n(6,360 feet above sea level)") +
  annotate("text", x=1962, y=6425,
           label = "unrestricted diversions\n(1941 - 1983)",
           size=3) +
  theme_minimal()
```


